from .StudentService import StudentService
from .auth.LicenseHolderAuthService import LicenseHolderAuthService
from .auth.StudentAuthService import StudentAuthService
from .LicenseHolderService import LicenseHolderService
